export const supportAreas = [
  {
    id: '01',
    name: 'Inbox management',
    shortName: 'Inbox',
    slug: 'inbox-management',
    line: 'Keep messages sorted, routine replies moving, and follow-ups from disappearing.',
    answer: 'Your Allo Assistant triages incoming messages, flags decisions, drafts routine replies, and keeps promised follow-ups moving.',
    bestFor: 'Founders whose inbox has become a second job.',
    tags: ['Daily triage', 'Draft replies', 'Follow-up tracking'],
  },
  {
    id: '02',
    name: 'Calendar and scheduling',
    shortName: 'Calendar',
    slug: 'calendar-scheduling',
    line: 'Turn a crowded schedule into a workday with room to think.',
    answer: 'Your Allo Assistant coordinates meetings, confirms participants, protects focus time, and prepares the details around each appointment.',
    bestFor: 'Busy teams coordinating clients, travel, and internal meetings.',
    tags: ['Scheduling', 'Coordination', 'Travel planning'],
  },
  {
    id: '03',
    name: 'Operations support',
    shortName: 'Operations',
    slug: 'operations-support',
    line: 'Keep recurring admin, reports, files, and CRM details in order.',
    answer: 'Your Allo Assistant owns repeatable operational tasks such as CRM updates, research, reporting preparation, file organisation, and recurring admin.',
    bestFor: 'Small teams with important processes but no dedicated operations coordinator.',
    tags: ['CRM updates', 'Research', 'Reporting'],
  },
  {
    id: '04',
    name: 'Customer support',
    shortName: 'Customer',
    slug: 'customer-support',
    line: 'Give routine questions and customer follow-ups a reliable owner.',
    answer: 'Your Allo Assistant handles routine enquiries, order or service updates, issue logging, and clear escalation when your decision is needed.',
    bestFor: 'Service and ecommerce teams that need responsive support without a full department.',
    tags: ['Customer care', 'Order updates', 'Escalation'],
  },
]
